services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      # The @ in the password has been changed to %40
      - DATABASE_URL=postgresql://Viswanath:Viswanath%401@db:5432/aitutorDB
    depends_on:
      - db
      - cache

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=Viswanath
      - POSTGRES_PASSWORD=Viswanath@1
      - POSTGRES_DB=aitutorDB
    ports:
      - "5432:5432"

  cache:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
